### ISSUE TITLE
计划拿什么语言写这个啊

### ISSUE THREAD

**Issue by miaomiaocoder** [wmathor/Rubbish-Video-Generator#1]

**Comment by wmathor** [comment]
> _No description provided._

已经写完了，用的python，正在写readme，大概下午就push

**Comment by miaomiaocoder** [comment]
python我还是搞不来的（枯了），期待c++项目

**Comment by wmathor** [comment]
> python我还是搞不来的（枯了），期待c++项目

C++我也搞不来的（枯了）
